[tool.pdm]

[project]
name = ""
version = ""
description = ""
authors = [{ name = "Donald33 Wang", email = "donald33wang@gmail.com" }]
dependencies = ["reportlab>=4.0.4", "pygame>=2.5.0"]
requires-python = ">=3.11"
license = { text = "MIT" }
