[tool.pdm]

[project]
name = ""
version = ""
description = ""
authors = [{ name = "Donald33 Wang", email = "donald33wang@gmail.com" }]
dependencies = ["reportlab>=3.6.12", "pygame>=2.1.3"]
requires-python = ">=3.11"
license = { text = "MIT" }
